USE [Kabel]
GO

/****** Object:  StoredProcedure [dbo].[AtualizaAnaliseLocalOptcode]    Script Date: 07/07/2023 17:19:50 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO













CREATE PROCEDURE [dbo].[AtualizaAnaliseLocalOptcode](@RECNO_EST_LOCAL INT,@QTDE DECIMAL(19,4), @ODF INT, @ITEM VARCHAR(20), @LOTE VARCHAR(40))
AS
	DECLARE @RECNO_ANALISE INT
	DECLARE @RECNO_ANAL_LOCAL INT
	DECLARE @FATOR DECIMAL(19,4)
	DECLARE @SALDO_HISREAL DECIMAL (19,6)
	DECLARE @QTDE_MAX_1565 DECIMAL(19,6)
	DECLARE @RECNO_HISREAL INT
	DECLARE @PECA VARCHAR(50)
	DECLARE @VALIDA_SALDO_ANAL_LOCAL DECIMAL(19,6)
	DECLARE @RECNO_LOCAL_DESTINO INT
	DECLARE @SALDOLOCALORIGEM DECIMAL(19,6)
	DECLARE @SALDOLOCALDESTINO DECIMAL(19,6)

	SELECT @RECNO_ANALISE = R_E_C_N_O_, @FATOR = FATOR, @PECA=PECA FROM ANALISE (NOLOCK) WHERE ODF = @ODF AND ITEM = @ITEM

	SELECT @RECNO_ANAL_LOCAL = R_E_C_N_O_ FROM ANALISE_LOCAL (NOLOCK) 
	WHERE ODF = @ODF 
	  AND ITEM = @ITEM 
	  AND LOTE = @LOTE 
	  AND LOCAL = '4754'


 SELECT @VALIDA_SALDO_ANAL_LOCAL = (QTDE - @QTDE), @QTDE_MAX_1565 =QTDE FROM ANALISE_LOCAL (NOLOCK) WHERE ODF = @ODF AND ITEM = @ITEM AND LOCAL = '1565' AND PRIORIDADE_CONSUMO = '1'

	IF @VALIDA_SALDO_ANAL_LOCAL < 0
	BEGIN
	  SET @QTDE=@QTDE_MAX_1565
		--ROLLBACK TRANSACTION
		--RAISERROR('Operação abortada',16,1)
	END


	IF @RECNO_ANAL_LOCAL IS NULL
	BEGIN
		INSERT INTO ANALISE_LOCAL(ITEM,LOCAL,ODF,QTDE,FATOR,LOTE,EMPRESA_RECNO,PRIORIDADE_CONSUMO,RECNO_ANALISE,PECA)
		 VALUES (@ITEM,'4754',@ODF,@QTDE,@FATOR,@LOTE,'1','0',@RECNO_ANALISE,@PECA)
	END
	ELSE
	BEGIN
		UPDATE ANALISE_LOCAL SET QTDE = QTDE + @QTDE WHERE R_E_C_N_O_ = @RECNO_ANAL_LOCAL
	END

	


	UPDATE ANALISE_LOCAL SET QTDE = QTDE - @QTDE WHERE ODF = @ODF AND ITEM = @ITEM AND LOCAL = '1565' AND PRIORIDADE_CONSUMO = '1'
	DELETE FROM ANALISE_LOCAL WHERE ODF = @ODF AND ITEM = @ITEM AND LOCAL = '1565' AND QTDE = 0
   
   --Os updates abaixo foi incluído com base no profiler da execução da rotina do Valmir
	exec CST_GRAVAR_QTDE_APONTADA @ITEM , @ODF 

	--fim do update com base no profile da rotina do Valmir

	DELETE FROM CST_LOTES_MOVIMENTACAO_OPTCODE WHERE RECNO_ESTOQUE_LOCAL= @RECNO_EST_LOCAL

		UPDATE ESTOQUE_LOCAL SET QTDE = QTDE - @QTDE WHERE R_E_C_N_O_ = @RECNO_EST_LOCAL

    SELECT @RECNO_LOCAL_DESTINO =R_E_C_N_O_ FROM ESTOQUE_LOCAL(NOLOCK) WHERE CODIGO=@ITEM AND LOTE=@LOTE AND LOCAL='4754' --BUSCA O recno do local de destino do lote no local 4754 para atualizar o saldo
	IF @RECNO_LOCAL_DESTINO IS NOT NULL -- se já existe um saldo do lote no local 4754, apenas aumenta o saldo no local de destino
	BEGIN
	  UPDATE ESTOQUE_LOCAL SET QTDE = QTDE + @QTDE WHERE R_E_C_N_O_ = @RECNO_LOCAL_DESTINO
	END
	ELSE -- se não existe cria o saldo no local de destino
	BEGIN
	 INSERT INTO ESTOQUE_LOCAL(CODIGO,LOCAL,QTDE,LOTE,DTCRIACAO,DTFABRICACAO,VALIDADE,CODIGO_ARMAZEM,QTDE_SAIDA,QTDE_ENTRADA,EMPRESA_RECNO,DATAHORA_REG,RECNO_LOCAIS,ODF,PESO_BRUTO,PESO_LIQUIDO) VALUES(@ITEM,'4754',@QTDE,@LOTE,CONVERT(CHAR(8),GETDATE(),112),'','','KM',0,@QTDE,1,GETDATE(),45342,@ODF,0,0)
	END


	SELECT @SALDOLOCALORIGEM=SUM(ISNULL(QTDE,0)) FROM ESTOQUE_LOCAL EL(NOLOCK) WHERE CODIGO=@ITEM AND LOCAL='1565' AND LOTE=@LOTE 
	SELECT @SALDOLOCALDESTINO=SUM(ISNULL(QTDE,0)) FROM ESTOQUE_LOCAL EL(NOLOCK) WHERE CODIGO=@ITEM AND LOCAL='4754' AND LOTE=@LOTE
	

	INSERT INTO HISREAL(CODIGO,DOCUMEN,DTRECEB,QTRECEB,VALPAGO,SALDO,SALDO_EMPRESA,FORMA,ODF,DATA,USUARIO,LOTE,LOCAL_DESTINO,LOCAL_ORIGEM,CUSTO_MEDIO,CUSTO_TOTAL,CUSTO_UNITARIO,CATEGORIA,DESCRICAO,FAMILIA,UNIDADE,EMPRESA_RECNO,ESTORNADO_APT_PRODUCAO,ESTORNO_ALOCACAO,TROCA_SALDO_PRODUTO)
		SELECT E.CODIGO, 'Transferência Aut.',CONVERT(CHAR(8),GETDATE(),112),@QTDE,EMP.VALPAGO, EMP.SALDOREAL, EMP.SALDOREAL, 'P',
			   @ODF, GETDATE(),'JOB OptCode',@LOTE, '4754','1565',EMP.CUSTO_MEDIO,EMP.CUSTO_TOTAL,EMP.CUSTO_UNITARIO,
			   E.CATEGORIA, E.DESCRI, E.FAMILIA, E.UNIDADE, '1','N','N','N' FROM ESTOQUE E (NOLOCK) 
		INNER JOIN ESTOQUE_EMPRESA EMP (NOLOCK) ON EMP.CODIGO = E.CODIGO
		WHERE E.CODIGO = @ITEM

	
		--SELECT @SALDO_HISREAL = SALDO, @RECNO_HISREAL = R_E_C_N_O_ FROM HISREAL (NOLOCK) WHERE R_E_C_N_O_ IN (
	    --		SELECT MAX(R_E_C_N_O_) AS RECNO FROM HISREAL (NOLOCK) WHERE CODIGO = @ITEM AND LOTE = @LOTE AND USUARIO = 'JOB OptCode')

	INSERT INTO HISLOCAL(DATAHORA,USUARIO,CODIGO,LOCAL,FORMA,QTDE,SALDO,RECNO_HISREAL,LOTE,CODIGO_ARMAZEM,EMPRESA_RECNO)
		SELECT GETDATE(), 'JOB OptCode', @ITEM,'1565', 'S', @QTDE, @SALDOLOCALORIGEM, @RECNO_HISREAL, @LOTE, 'KM', '1'

	INSERT INTO HISLOCAL(DATAHORA,USUARIO,CODIGO,LOCAL,FORMA,QTDE,SALDO,RECNO_HISREAL,LOTE,CODIGO_ARMAZEM,EMPRESA_RECNO)
		SELECT GETDATE(), 'JOB OptCode', @ITEM,'4754', 'E', @QTDE, @SALDOLOCALDESTINO, @RECNO_HISREAL, @LOTE, 'KM', '1'





	
	

GO


