USE [Kabel]
GO

/****** Object:  StoredProcedure [dbo].[gerarFifoLoteOptCode]    Script Date: 07/07/2023 17:19:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO














CREATE PROCEDURE [dbo].[gerarFifoLoteOptCode](@sCodigoItem VARCHAR(50), @dQtdeMovimentacao DECIMAL(19,4), @ODF INT)
AS
	DECLARE @QTDE DECIMAL(19,4)
	DECLARE @LOTE VARCHAR(50)
	DECLARE @REGISTROS INT
	DECLARE @SALDOTOTAL DECIMAL(19,4)
	DECLARE @NECES DECIMAL(19,4)
	DECLARE @QTDE_1565 DECIMAL(19,4)
	DECLARE @RECNO_EST_LOCAL INT
	SET @NECES = @dQtdeMovimentacao
	


	DELETE CST_LOTES_MOVIMENTACAO_OPTCODE -- WHERE ITEM=@sCodigoItem 
	
	SELECT @SALDOTOTAL = SUM(QTDE), @REGISTROS = COUNT(*) FROM ESTOQUE_LOCAL (NOLOCK) 
		WHERE CODIGO = @sCodigoItem
		 AND LOCAL = 1565
		 AND QTDE > 0

   IF @SALDOTOTAL =NULL
	BEGIN
	 SET @SALDOTOTAL=0
	 SET @REGISTROS=0
	END

	IF @SALDOTOTAL < @dQtdeMovimentacao
	BEGIN
		SET @NECES = @SALDOTOTAL
	END

	IF @REGISTROS = 1
	BEGIN
		SELECT @RECNO_EST_LOCAL = R_E_C_N_O_, @LOTE = LOTE FROM ESTOQUE_LOCAL (NOLOCK) 
		WHERE CODIGO = @sCodigoItem
		 AND LOCAL = 1565
		 AND QTDE > 0
		INSERT INTO CST_LOTES_MOVIMENTACAO_OPTCODE(QTDE,ITEM,LOTE,RECNO_ESTOQUE_LOCAL,NUMODF) VALUES (@dQtdeMovimentacao, @sCodigoItem, @LOTE, @RECNO_EST_LOCAL,@ODF)
		
	     SELECT @QTDE_1565=QTDE FROM ANALISE_LOCAL(NOLOCK) WHERE ITEM=@sCodigoItem  AND ODF=@ODF AND LOCAL='1565'
		 IF @QTDE_1565 IS NULL
		 BEGIN
		  SET @QTDE_1565 =0
		 END
		 
		 IF @QTDE_1565 < @NECES
		 BEGIN
		   SET @NECES=@QTDE_1565
		   SET @QTDE=@QTDE_1565
		 END
		
		EXEC AtualizaAnaliseLocalOptcode @RECNO_EST_LOCAL, @dQtdeMovimentacao, @ODF, @sCodigoItem,@LOTE
	END
	ELSE
		BEGIN 
	     WHILE @NECES > 0  --100  (4 LOTES DE 25)  LOTE DE 25 Nº 1
		 BEGIN
			SELECT TOP 1 @QTDE = EL.QTDE-ISNULL(CST.QTDE,0), @LOTE = EL.LOTE, @RECNO_EST_LOCAL = R_E_C_N_O_ FROM ESTOQUE_LOCAL EL (NOLOCK) 
			LEFT JOIN (SELECT SUM(ISNULL(QTDE,0)) AS QTDE,ITEM,LOTE,NUMODF,RECNO_ESTOQUE_LOCAL FROM  CST_LOTES_MOVIMENTACAO_OPTCODE(NOLOCK) GROUP BY QTDE,ITEM,LOTE,NUMODF,RECNO_ESTOQUE_LOCAL ) CST  ON CST.RECNO_ESTOQUE_LOCAL = EL.R_E_C_N_O_
			WHERE CODIGO = @sCodigoItem
			 AND EL.LOCAL = 1565
			 AND EL.QTDE > 0
			 AND CST.RECNO_ESTOQUE_LOCAL IS NULL --OR ((CST.RECNO_ESTOQUE_LOCAL IS NULL) AND (EL.QTDE >CST.QTDE))
			 
			ORDER BY EL.DTCRIACAO,EL.LOTE ASC

			IF @NECES <= @QTDE 
			BEGIN
				SET @QTDE = @NECES
				SET @NECES = 0
			END
			ELSE
			BEGIN
				SET @NECES = @NECES - @QTDE		
			END

			IF @QTDE IS NOT NULL 
			BEGIN
			  INSERT INTO CST_LOTES_MOVIMENTACAO_OPTCODE(QTDE,ITEM,LOTE,RECNO_ESTOQUE_LOCAL,NUMODF) VALUES (@QTDE, @sCodigoItem, @LOTE, @RECNO_EST_LOCAL,@ODF)
		   END
		    SELECT @QTDE_1565=QTDE FROM ANALISE_LOCAL(NOLOCK) WHERE ITEM=@sCodigoItem  AND ODF=@ODF AND LOCAL='1565'
			IF @QTDE_1565 IS NULL
			BEGIN
				SET @QTDE_1565 =0
			END

			 IF @QTDE_1565 < @NECES
			BEGIN
			SET @NECES=@QTDE_1565
			SET @QTDE=@QTDE_1565
			END
			EXEC AtualizaAnaliseLocalOptcode @RECNO_EST_LOCAL, @QTDE, @ODF, @sCodigoItem,@LOTE

		 END





	END


	

GO


