BEGIN TRAN
DECLARE @INT INT
DECLARE @CONT INT
DECLARE @KIT INT
DECLARE @CODIGO_ANTERIOR VARCHAR(15)
DECLARE @RECNO INT
SET @CODIGO_ANTERIOR = 'MA0002'
SET @CONT = 1
SET @INT = (SELECT COUNT(*) FROM CST_CAD_MM_APLIC)

WHILE @CONT <= @INT
BEGIN
	IF (SELECT TOP 1 codigo_ma FROM CST_CAD_MM_APLIC WHERE KIT IS NULL order by codigo_ma) = @CODIGO_ANTERIOR
	BEGIN
		SELECT @KIT = MAX(KIT)+1 FROM CST_CAD_MM_APLIC WHERE CODIGO_MA = @CODIGO_ANTERIOR AND KIT IS NOT NULL
		SELECT TOP 1 @RECNO = R_E_C_N_O_ FROM CST_CAD_MM_APLIC WHERE CODIGO_MA = @CODIGO_ANTERIOR AND KIT IS NULL GROUP BY R_E_C_N_O_,CODIGO_MA ORDER BY CODIGO_MA
		UPDATE CST_CAD_MM_APLIC SET KIT = @KIT WHERE R_E_C_N_O_ = @RECNO
	END
	ELSE
	BEGIN
		SELECT TOP 1 @RECNO = R_E_C_N_O_, @KIT = ISNULL(MAX(KIT),1),@CODIGO_ANTERIOR = CODIGO_MA FROM CST_CAD_MM_APLIC WHERE KIT IS NULL GROUP BY R_E_C_N_O_,CODIGO_MA ORDER BY CODIGO_MA
		UPDATE CST_CAD_MM_APLIC SET KIT = @KIT WHERE R_E_C_N_O_ = @RECNO
	END
	PRINT CONCAT(@CODIGO_ANTERIOR,', KIT: ',@KIT,', RECNO: ', @RECNO,' Contador: ',@CONT)
	SET @CONT = @CONT + 1
END

ROLLBACK
COMMIT TRAN
